const ProjectsList = [
  {
    name: "Project 1",
    url: "p1",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
  {
    name: "Project 1",
    url: "p2",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
  {
    name: "Project 1",
    url: "p3",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
  {
    name: "Project 1",
    url: "p4",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
  {
    name: "Project 1",
    url: "p5",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
  {
    name: "Project 1",
    url: "p6",
    image: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
    desc: "Lorem ipsum dolor sit am.",
    category: "Web",
    date: "11-April-2020",
    link: "https://www.satakshigarg.in/assets/img/portfolio/portfolio-4.jpg",
  },
];

export default ProjectsList;
