const ProjectsList = [
  {
    name: "Codeforces-Visualizer",
    title: "Analyzes codeforces profile ",
    url: "p1",
    image: "visualizer.PNG",
    date: "21-04-2022",
    desc: "This application analyzes codeforces account and give information about user profile, submissions, contests, problems etc.",
    tech: "React, React-Redux, Codeforces APIs",
    category: "Web",
    website: "https://21omkarsase.github.io/Codeforces-Visualizer/",
    github: "https://github.com/21omkarsase/Codeforces-Visualizer",
  },
  {
    name: "Task Manager",
    title: "Task Manager (CRUD Tasks)",
    url: "p2",
    image: "",
    date: "21-04-2022",
    desc: "This application helps to manage tasks. We can keep track of all our tasks. It provides options of create, update, delete task.",
    tech: "Nodejs, Express, Mongodb, HBS",
    category: "Web",
    website: "https://omkar-task-manager-app.herokuapp.com",
    github: "https://github.com/21omkarsase/Task-Manager",
  },
  {
    name: "Chat App",
    title: "Web Application for group chatting/messaging",
    url: "p3",
    image: "",
    date: "21-04-2022",
    desc: "We can create chat rooms for group or one-to-one chatting",
    tech: "Express, Socket-IO, HBS",
    category: "Web",
    website: "https://chat-app-omkar.herokuapp.com/",
    github: "https://github.com/21omkarsase/Chat-App",
  },
  {
    name: "Weather App",
    title: "Gives weather information",
    url: "p4",
    image: "",
    date: "21-04-2022",
    desc: "Here we get information about weather by giving location as a input for which we want weather information",
    tech: "Express Node HBS Weather-APIs",
    category: "Web",
    website: "https://weather-app-omkar.herokuapp.com/",
    github: "https://github.com/21omkarsase/Weather-Application",
  },
  {
    name: "Expense Tracker",
    title: "Keeps track of expenses",
    url: "p5",
    image: "",
    date: "21-04-2022",
    desc: "Helps to keep track of expenses by providing interactive interface and well distributed split of your expenses",
    tech: "React",
    category: "Web",
    website: "https://21omkarsase.github.io/Expense-Tracker/",
    github: "https://github.com/21omkarsase/Expense-Tracker",
  },
  {
    name: "DSA",
    title: "Data Structure And Algorithms",
    url: "p6",
    image: "",
    date: "21-04-2022",
    desc: "Github repository which includes data structure and algorithms problems solved by me",
    tech: "C++, Data Structures, Algorithms",
    category: "Web",
    github: "https://github.com/21omkarsase/DSA",
  },
];

export default ProjectsList;
