export const PROJECTS_REQUEST_STARTED = "PROJECTS_REQUEST_STARTED";
export const PROJECTS_REQUEST_SUCCESS = "PROJECTS_REQUEST_SUCCESS";
export const PROJECTS_REQUEST_FAILED = "PROJECTS_REQUEST_FAILED";

export const PROJECT_REQUEST_STARTED = "PROJECT_REQUEST_STARTED";
export const PROJECT_REQUEST_SUCCESS = "PROJECT_REQUEST_SUCCESS";
export const PROJECT_REQUEST_FAILED = "PROJECT_REQUEST_FAILED";
